# Generated by Django 3.1.7 on 2021-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(choices=[('a', 'Accepted'), ('b', 'Ongoing'), ('c', 'Bonjour'), ('d', 'Boas')], max_length=1)),
            ],
        ),
    ]
