# Generated by Django 3.1.7 on 2021-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acase',
            name='info',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acase',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
