# Generated by Django 3.1.7 on 2021-03-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210318_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acase',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Ongoing', 'Ongoing')], max_length=100),
        ),
    ]
