# Generated by Django 3.1.7 on 2021-04-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210318_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acase',
            old_name='info',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='acase',
            old_name='name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='acase',
            name='status',
        ),
        migrations.AddField(
            model_name='acase',
            name='district',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acase',
            name='firstname',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acase',
            name='landmark',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acase',
            name='lastname',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acase',
            name='locality',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acase',
            name='state',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acase',
            name='zipcode',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acase',
            name='image',
            field=models.ImageField(upload_to='images/case'),
        ),
    ]
