# Generated by Django 3.1.7 on 2021-04-01 17:49

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210401_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='acase',
            name='phoneno',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acase',
            name='image',
            field=models.ImageField(upload_to=dashboard.models.case_directory_path),
        ),
    ]
