# Generated by Django 3.1.7 on 2021-04-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='acase',
            name='emailid',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
