# Generated by Django 3.1.7 on 2021-04-05 19:32

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_acase_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='detect_missing',
            fields=[
                ('detectedcase_no', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=dashboard.models.missed_directory_path)),
                ('landmark', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
            ],
        ),
    ]
