# Generated by Django 3.1.7 on 2021-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_detected_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='detected_missing',
            name='casefromacase',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
