# Generated by Django 3.1.7 on 2021-04-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_detected_missing_casefromacase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detected_missing',
            name='emailid',
        ),
    ]
