# Generated by Django 3.1.7 on 2021-04-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_detected_missing_emailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detected_missing',
            name='casefromacase',
        ),
        migrations.AddField(
            model_name='detected_missing',
            name='caseidentifier',
            field=models.CharField(default='a', max_length=300),
            preserve_default=False,
        ),
    ]
