# Generated by Django 3.1.7 on 2021-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210406_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='detected_missing',
            name='firstname',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detected_missing',
            name='lastname',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detected_missing',
            name='phoneno',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
