# Generated by Django 3.1.7 on 2021-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210406_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='detected_missing',
            name='time_detected',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
