# Generated by Django 3.1.7 on 2021-04-07 15:42

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_detected_missing_time_detected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected_missing',
            name='image',
            field=models.ImageField(unique=True, upload_to=dashboard.models.missed_directory_path),
        ),
    ]
