# Generated by Django 3.1.7 on 2021-04-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210407_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='track_vehicle',
            fields=[
                ('case', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=300)),
            ],
        ),
    ]
