# Generated by Django 3.1.7 on 2021-04-14 06:20

from django.db import migrations, models
import vehicle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detected_missing',
            fields=[
                ('detected_no', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=200)),
                ('image', models.ImageField(unique=True, upload_to=vehicle.models.missed_directory_path)),
                ('landmark', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('time_detected', models.CharField(max_length=100)),
            ],
        ),
    ]
