# Generated by Django 3.1.7 on 2021-04-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detected_missing',
            new_name='detected_missing_vehicle',
        ),
    ]
