# Generated by Django 3.1.7 on 2021-04-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20210414_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected_missing_vehicle',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detected_missing_vehicle',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detected_missing_vehicle',
            name='landmark',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detected_missing_vehicle',
            name='locality',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detected_missing_vehicle',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detected_missing_vehicle',
            name='time_detected',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detected_missing_vehicle',
            name='zipcode',
            field=models.CharField(max_length=200),
        ),
    ]
