# Generated by Django 3.1.7 on 2021-04-14 07:20

from django.db import migrations, models
import vehicle.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20210414_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected_missing_vehicle',
            name='image',
            field=models.ImageField(max_length=500, unique=True, upload_to=vehicle.models.missed_directory_path),
        ),
    ]
